# Generated by Django 4.1.3 on 2023-08-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="news",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=20)),
                ("category", models.IntegerField()),
                ("image_url", models.CharField(max_length=50)),
                ("editor", models.CharField(max_length=50)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.text"
                    ),
                ),
            ],
        ),
    ]
